baseurl = "/"
languageCode = "en-us"
title = "chmanie"
theme = "xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "random texts written by Christian Maniewski"
    footer = "&copy; Christian Maniewski 2020-2022 | [email](mailto:machine@chmanie.com) | [SourceHut](https://git.sr.ht/~chmanie) | [Github](https://github.com/chmanie) | [Twitter](https://twitter.com/chmanie)"
